services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash -c "export SPRING_DATASOURCE_PASSWORD=$(cat /run/secrets/db-password) && java org.springframework.boot.loader.launch.JarLauncher"
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/tasktrackerrestapi?createDatabaseIfNotExist=true
      - spring.datasource.username=postgres
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.password=guest
      - spring.rabbitmq.username=guest
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db-password
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  postgres:
    image: postgres:17.0
    restart: "no"
    ports:
      - "5432:5432"
    secrets:
      - db-password
    volumes:
      - type: volume
        source: postgres_data
        target: "/var/lib/postgresql/data"
      - ./db/cleandb.sql:/scripts/cleandb.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: tasktrackerrestapi
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:4.0.2-management
    restart: "no"
    ports:
      - "5433:5432"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  newman:
    image: postman/newman
    volumes:
      - type: bind
        source: ./postman
        target: /etc/newman
    entrypoint: [
      "newman",
      "run",
      "task-tracker-rest-api tests.postman_collection.json",
      "-e",
      "http-host.docker.internal-8080.postman_environment.json"
    ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      app:
        condition: service_healthy
volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:

secrets:
  db-password:
    file: db/password.txt