name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Publish to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sergeystol/task-tracker-rest-api
          registry: docker.io
          tags: ${BRANCH_NAME}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repoea
        uses: actions/checkout@v3
      - name: run test stack
        run: docker compose -f docker-compose-tests.yaml up --exit-code-from newman
