name: CD pipeline

on: ["push"]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run smoke tests with uber jar
        run: |
          docker compose -f docker-compose-tests.yaml up --build --abort-on-container-exit
          docker compose -f docker-compose-tests.yaml down --volumes --remove-orphans
      - name: Run smoke tests with layered jar
        run: |
          docker compose up newman --build --abort-on-container-exit --exit-code-from newman -V
          docker compose --profile app down --volumes --remove-orphans
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build and test with Maven
        run: mvn clean install
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get branch name
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sergeystol/task-tracker-rest-api:${{ steps.branch-names.outputs.current_branch }}